# Generated by Django 5.0.14 on 2026-10-06 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_alter_cliente_id_alter_color_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="cajero",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="venta",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
