# Generated by Django 5.0.14 on 2026-10-08 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_cliente_activo_color_activo_proveedor_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='proveedores',
            field=models.ManyToManyField(limit_choices_to={'activo': True}, related_name='ropas', to='tienda.proveedor'),
        ),
        migrations.AlterField(
            model_name='ropa',
            name='tipo',
            field=models.ForeignKey(limit_choices_to={'activo': True}, on_delete=django.db.models.deletion.RESTRICT, to='tienda.tipo'),
        ),
    ]
